// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    acompanhamento: {
        name: "acompanhamento";
        parameters: Record<string, never>;
        result: Array<{
          /** Id do vendedor dono da carteira. E a chave de verdade: ha nomes repetidos na base (dois Henrique Oliveira, dois Vinicius Lopes), entao agrupar por nome funde carteiras de pessoas diferentes. */
          vendedor_id: number;
          /** Nome do vendedor, para leitura. Nao e unico -- use vendedor_id para agrupar. Seis dos 42 vendedores estao desligados e nao aparecem aqui. */
          vendedor: string;
          /** @sqlType BIGINT */
          na_fila: number;
          /** @sqlType BIGINT */
          trabalhados: number;
          /** @sqlType BIGINT */
          vendeu: number;
          /** @sqlType BIGINT */
          vai_pensar: number;
          /** @sqlType BIGINT */
          sem_interesse: number;
          /** @sqlType BIGINT */
          nao_atendeu: number;
        }>;
      };
    fila: {
        name: "fila";
        parameters: {
          /** STRING - use sql.string() */
          vendedor_id: SQLStringMarker;
        };
        result: Array<{
          /** Ordem de ligacao DENTRO da carteira do vendedor, do maior score para o menor. */
          ordem: number;
          /** Cliente a ligar. E a chave que liga esta fila a gold.retorno_ligacao, onde o time registra o que aconteceu depois. */
          cliente_id: number;
          /** initcap e espaco duplo colapsado. A origem mistura caixa alta, baixa e espacamento irregular. */
          razao_social: string;
          /** Cidade do cliente, para o vendedor se situar antes de ligar. Grafia livre na origem -- para agrupar, use uf. */
          cidade: string;
          /** UF do cliente. E o corte geografico confiavel da fila. */
          uf: string;
          /** Receita dividida por pedidos distintos. */
          ticket_medio: number;
          /** Id do vendedor dono da carteira. E a chave de verdade: ha nomes repetidos na base (dois Henrique Oliveira, dois Vinicius Lopes), entao agrupar por nome funde carteiras de pessoas diferentes. */
          vendedor_id: number;
          /** Nome do vendedor, para leitura. Nao e unico -- use vendedor_id para agrupar. Seis dos 42 vendedores estao desligados e nao aparecem aqui. */
          vendedor: string;
          /** Probabilidade de compra nos proximos 7 dias, vinda de gold.score_propensao. */
          score: number;
          /** Quartil do score: Fria, Morna, Quente, Muito quente. Serve para conversar com o comercial sem falar em probabilidade. */
          faixa: string;
          /** Frase em portugues explicando por que o cliente esta na fila, com os numeros reais dele. Nunca nula. */
          motivo: string;
          /** O que oferecer: o SKU mais comprado na marca preferida que o cliente nao leva ha 90 dias, com o saldo do ultimo snapshot daquele SKU. */
          sugestao: string;
          /** Resultado da ligacao, conjunto fechado: vendeu, vai_pensar, sem_interesse ou nao_atendeu. Conversao e status = 'vendeu'. */
          retorno_status: string;
          /** Texto livre do vendedor sobre a conversa. Pode ser nulo -- registrar o resultado sem comentar e valido. */
          retorno_comentario: string;
          /** Momento do registro. E o criterio de desempate quando o mesmo cliente tem mais de um retorno: o estado atual e o mais recente. */
          retorno_em: string;
        }>;
      };
    kpis_semana: {
        name: "kpis_semana";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          contatos: number;
          /** @sqlType BIGINT */
          vendedores: number;
          /** @sqlType DOUBLE */
          receita_esperada: number;
          /** @sqlType TIMESTAMP */
          referencia: string;
          /** Quantos dos 200 melhores compraram de fato, medido out-of-fold. */
          acertos_top200: number;
          /** Quantas vezes a fila de 200 supera o acaso. E a metrica que responde o diretor. */
          lift_top200: number;
          /** Fracao de clientes que compra na semana sem modelo nenhum. */
          taxa_base: number;
          /** Versao registrada no Unity Catalog. */
          versao_modelo: number;
          /** @sqlType BIGINT */
          retornos: number;
          /** @sqlType BIGINT */
          viraram_pedido: number;
        }>;
      };
    vendedores: {
        name: "vendedores";
        parameters: Record<string, never>;
        result: Array<{
          /** Id do vendedor dono da carteira. E a chave de verdade: ha nomes repetidos na base (dois Henrique Oliveira, dois Vinicius Lopes), entao agrupar por nome funde carteiras de pessoas diferentes. */
          vendedor_id: number;
          /** Nome do vendedor, para leitura. Nao e unico -- use vendedor_id para agrupar. Seis dos 42 vendedores estao desligados e nao aparecem aqui. */
          vendedor: string;
          /** @sqlType BIGINT */
          contatos: number;
          /** @sqlType STRING */
          rotulo: string;
        }>;
      };
  }
}
